// <auto-generated />
using System;
using AdminBlog.EntityFramework.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminBlog.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20211227142625_v0.0.3")]
    partial class v003
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdminBlog.Core.Blog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BlogType")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("longtext");

                    b.Property<string>("Cover")
                        .HasColumnType("longtext");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FriendUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAllowedComments")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTop")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .HasColumnType("longtext");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PublishTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PublishType")
                        .HasColumnType("int");

                    b.Property<int>("ReadingVolume")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("AdminBlog.Core.Comment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BlogId")
                        .HasColumnType("bigint");

                    b.Property<string>("Browser")
                        .HasColumnType("longtext");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext");

                    b.Property<string>("HeadPortrait")
                        .HasColumnType("longtext");

                    b.Property<string>("IP")
                        .HasColumnType("longtext");

                    b.Property<string>("IPHome")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QQ")
                        .HasColumnType("longtext");

                    b.Property<string>("ShowName")
                        .HasColumnType("longtext");

                    b.Property<string>("Site")
                        .HasColumnType("longtext");

                    b.Property<string>("SystemVersion")
                        .HasColumnType("longtext");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("AdminBlog.Core.FriendlyLinks", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LinkType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FriendlyLinks");
                });

            modelBuilder.Entity("AdminBlog.Core.SysDictionary", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCanMultiple")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sys_Dictionary");

                    b.HasData(
                        new
                        {
                            Id = 160774000443461L,
                            Code = "BlogType",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 969, DateTimeKind.Unspecified).AddTicks(3915), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCanMultiple = false,
                            IsDeleted = false,
                            Name = "博客类型"
                        },
                        new
                        {
                            Id = 160776633155653L,
                            Code = "EmailType",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 969, DateTimeKind.Unspecified).AddTicks(3918), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCanMultiple = false,
                            IsDeleted = false,
                            Name = "邮箱类型"
                        },
                        new
                        {
                            Id = 169581276397637L,
                            Code = "BlogLabel",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 969, DateTimeKind.Unspecified).AddTicks(3919), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCanMultiple = true,
                            IsDeleted = false,
                            Name = "文章标签"
                        });
                });

            modelBuilder.Entity("AdminBlog.Core.SysDictionaryDetail", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailCode")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sys_Dictionary_Detail");

                    b.HasData(
                        new
                        {
                            Id = 160774000443461L,
                            Code = "BlogType",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3855), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "InformalEssay",
                            IsDeleted = false,
                            SortIndex = 0,
                            Value = "随笔"
                        },
                        new
                        {
                            Id = 160776633155653L,
                            Code = "BlogType",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3858), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "Article",
                            IsDeleted = false,
                            SortIndex = 1,
                            Value = "文章"
                        },
                        new
                        {
                            Id = 161765323022405L,
                            Code = "EmailType",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3859), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "TencentCompanyEmail",
                            IsDeleted = false,
                            SortIndex = 0,
                            Value = "腾讯企业邮箱"
                        },
                        new
                        {
                            Id = 161765323022406L,
                            Code = "EmailType",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3860), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "163FreeEmail",
                            IsDeleted = false,
                            SortIndex = 1,
                            Value = "163免费邮箱"
                        },
                        new
                        {
                            Id = 161765323022407L,
                            Code = "BlogLabel",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3861), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "Java",
                            IsDeleted = false,
                            SortIndex = 0,
                            Value = "Java"
                        },
                        new
                        {
                            Id = 161765323022408L,
                            Code = "BlogLabel",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3863), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "C#",
                            IsDeleted = false,
                            SortIndex = 1,
                            Value = "C#"
                        },
                        new
                        {
                            Id = 161765323022409L,
                            Code = "BlogLabel",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3864), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "NET Core",
                            IsDeleted = false,
                            SortIndex = 1,
                            Value = "NET Core"
                        },
                        new
                        {
                            Id = 161765323022410L,
                            Code = "BlogLabel",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3865), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "JS",
                            IsDeleted = false,
                            SortIndex = 1,
                            Value = "JS"
                        },
                        new
                        {
                            Id = 161765323022411L,
                            Code = "BlogLabel",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 970, DateTimeKind.Unspecified).AddTicks(3866), new TimeSpan(0, 0, 0, 0, 0)),
                            DetailCode = "Vue",
                            IsDeleted = false,
                            SortIndex = 1,
                            Value = "Vue"
                        });
                });

            modelBuilder.Entity("AdminBlog.Core.SysEmailConfig", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailType")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailUserName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SmtpUrl")
                        .HasColumnType("longtext");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Sys_EmailConfig");
                });

            modelBuilder.Entity("AdminBlog.Core.SysFile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DownTimes")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MD5Value")
                        .HasColumnType("longtext");

                    b.Property<string>("RealPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Site")
                        .HasColumnType("longtext");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sys_File");
                });

            modelBuilder.Entity("AdminBlog.Core.SysMenu", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Affix")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Affix");

                    b.Property<bool>("AlwaysShow")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("AlwaysShow");

                    b.Property<string>("Component")
                        .HasColumnType("longtext")
                        .HasColumnName("Component");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Hidden");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsUse")
                        .HasColumnType("int")
                        .HasColumnName("IsUse");

                    b.Property<string>("MenuCode")
                        .HasColumnType("longtext")
                        .HasColumnName("MenuCode");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("longtext")
                        .HasColumnName("MenuIcon");

                    b.Property<string>("MenuName")
                        .HasColumnType("longtext")
                        .HasColumnName("MenuName");

                    b.Property<string>("MenuPath")
                        .HasColumnType("longtext")
                        .HasColumnName("MenuPath");

                    b.Property<int>("MenuSource")
                        .HasColumnType("int")
                        .HasColumnName("MenuSource");

                    b.Property<string>("MenuTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("MenuTitle");

                    b.Property<int>("MenuType")
                        .HasColumnType("int")
                        .HasColumnName("MenuType");

                    b.Property<bool>("NoCache")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("NoCache");

                    b.Property<long>("ParentModuleID")
                        .HasColumnType("bigint")
                        .HasColumnName("ParentModuleID");

                    b.Property<string>("Redirect")
                        .HasColumnType("longtext")
                        .HasColumnName("Redirect");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int")
                        .HasColumnName("SortIndex");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sys_Menu");

                    b.HasData(
                        new
                        {
                            Id = 183496627462213L,
                            Affix = false,
                            AlwaysShow = true,
                            Component = "layout",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2579), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "BlogManager",
                            MenuIcon = "el-icon-notebook-1",
                            MenuName = "博客管理目录",
                            MenuPath = "/blog",
                            MenuSource = 0,
                            MenuTitle = "博客管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 0L,
                            SortIndex = 0
                        },
                        new
                        {
                            Id = 183500800106565L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "blog",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2583), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "BlogList",
                            MenuIcon = "el-icon-notebook-1",
                            MenuName = "博客管理",
                            MenuPath = "blog",
                            MenuSource = 0,
                            MenuTitle = "博客管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 183496627462213L,
                            SortIndex = 0
                        },
                        new
                        {
                            Id = 184831157919813L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "layout",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2584), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "System",
                            MenuIcon = "el-icon-s-operation",
                            MenuName = "系统管理",
                            MenuPath = "/system",
                            MenuSource = 0,
                            MenuTitle = "系统管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 0L,
                            SortIndex = 2
                        },
                        new
                        {
                            Id = 184831279587397L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "user",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2585), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "UserList",
                            MenuIcon = "el-icon-s-custom",
                            MenuName = "用户管理",
                            MenuPath = "users",
                            MenuSource = 0,
                            MenuTitle = "用户管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 184831157919813L,
                            SortIndex = 0
                        },
                        new
                        {
                            Id = 184831426105413L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "role",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2587), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "RoleList",
                            MenuIcon = "el-icon-user",
                            MenuName = "角色管理",
                            MenuPath = "roles",
                            MenuSource = 0,
                            MenuTitle = "角色管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 184831157919813L,
                            SortIndex = 1
                        },
                        new
                        {
                            Id = 184831587602501L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "menu",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2588), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "MenusList",
                            MenuIcon = "el-icon-menu",
                            MenuName = "菜单管理",
                            MenuPath = "menus",
                            MenuSource = 0,
                            MenuTitle = "菜单管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 184831157919813L,
                            SortIndex = 2
                        },
                        new
                        {
                            Id = 184831951908933L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "dictionary",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2590), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "Dic",
                            MenuIcon = "el-icon-notebook-2",
                            MenuName = "字典管理",
                            MenuPath = "dictionary",
                            MenuSource = 0,
                            MenuTitle = "字典管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 184831157919813L,
                            SortIndex = 3
                        },
                        new
                        {
                            Id = 184832096215109L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "waterfallImages",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2591), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = true,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "waterfallImages",
                            MenuIcon = "fa fa-image",
                            MenuName = "瀑布流图片",
                            MenuPath = "waterfallImages",
                            MenuSource = 0,
                            MenuTitle = "瀑布流图片",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 184831157919813L,
                            SortIndex = 4
                        },
                        new
                        {
                            Id = 188986113056837L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "createBlog",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2592), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = true,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "createBlog",
                            MenuIcon = "",
                            MenuName = "创建",
                            MenuPath = "createBlog",
                            MenuSource = 0,
                            MenuTitle = "博客详情",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 183496627462213L,
                            SortIndex = -2
                        },
                        new
                        {
                            Id = 188992024399941L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "editBlog",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2632), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = true,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "editBlog",
                            MenuIcon = "",
                            MenuName = "编辑",
                            MenuPath = "editBlog/:id",
                            MenuSource = 0,
                            MenuTitle = "博客详情",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 183496627462213L,
                            SortIndex = -1
                        },
                        new
                        {
                            Id = 189025873809477L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "uploadWaterfallImage",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2633), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "uploadWaterfallImage",
                            MenuIcon = "el-icon-picture",
                            MenuName = "上传图片",
                            MenuPath = "uploadWaterfallImage",
                            MenuSource = 0,
                            MenuTitle = "上传图片",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 184831157919813L,
                            SortIndex = 5
                        },
                        new
                        {
                            Id = 194102723149893L,
                            Affix = false,
                            AlwaysShow = false,
                            Component = "layout",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2634), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "LinksManager",
                            MenuIcon = "el-icon-link",
                            MenuName = "链接管理目录",
                            MenuPath = "/link",
                            MenuSource = 0,
                            MenuTitle = "链接管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 0L,
                            SortIndex = 1
                        },
                        new
                        {
                            Id = 194092013764677L,
                            Affix = false,
                            AlwaysShow = true,
                            Component = "links",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 974, DateTimeKind.Unspecified).AddTicks(2636), new TimeSpan(0, 0, 0, 0, 0)),
                            Hidden = false,
                            IsDeleted = false,
                            IsUse = 0,
                            MenuCode = "FriendlyLinks",
                            MenuIcon = "el-icon-link",
                            MenuName = "友链管理",
                            MenuPath = "links",
                            MenuSource = 0,
                            MenuTitle = "友链管理",
                            MenuType = 0,
                            NoCache = false,
                            ParentModuleID = 194102723149893L,
                            SortIndex = 1
                        });
                });

            modelBuilder.Entity("AdminBlog.Core.SysRole", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AdminFlag")
                        .HasColumnType("int")
                        .HasColumnName("AdminFlag");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsUse")
                        .HasColumnType("int")
                        .HasColumnName("IsUse");

                    b.Property<string>("RoleDesc")
                        .HasColumnType("longtext")
                        .HasColumnName("RoleDesc");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext")
                        .HasColumnName("RoleName");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sys_Role");

                    b.HasData(
                        new
                        {
                            Id = 156951674213412L,
                            AdminFlag = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 975, DateTimeKind.Unspecified).AddTicks(2186), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsUse = 0,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("AdminBlog.Core.SysRoleMenu", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("MenuID")
                        .HasColumnType("bigint")
                        .HasColumnName("MenuID");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleID");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sys_RoleMenu");
                });

            modelBuilder.Entity("AdminBlog.Core.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripts")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descripts");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsOnline")
                        .HasColumnType("int")
                        .HasColumnName("IsOnline");

                    b.Property<int>("IsUse")
                        .HasColumnType("int")
                        .HasColumnName("IsUse");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("longtext")
                        .HasColumnName("LastLoginIP");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastLoginTime");

                    b.Property<int>("LoginTimes")
                        .HasColumnType("int")
                        .HasColumnName("LoginTimes");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserLoginName")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("UserLoginName");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UserPassword");

                    b.HasKey("Id");

                    b.ToTable("Sys_User");

                    b.HasData(
                        new
                        {
                            Id = 156951674213412L,
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 977, DateTimeKind.Unspecified).AddTicks(4009), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsOnline = 0,
                            IsUse = 0,
                            LoginTimes = 0,
                            UserLoginName = "Admin",
                            UserPassword = "728AD9902AECBA32E22F"
                        });
                });

            modelBuilder.Entity("AdminBlog.Core.SysUserInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BirthDate");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext")
                        .HasColumnName("EMail");

                    b.Property<string>("HeadPortrait")
                        .HasColumnType("longtext")
                        .HasColumnName("HeadPortrait");

                    b.Property<string>("IDCard")
                        .HasColumnType("longtext")
                        .HasColumnName("IDCard");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("Phone");

                    b.Property<string>("QQ")
                        .HasColumnType("longtext")
                        .HasColumnName("QQ");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<string>("UserShowName")
                        .HasColumnType("longtext")
                        .HasColumnName("UserShowName");

                    b.Property<string>("WeChat")
                        .HasColumnType("longtext")
                        .HasColumnName("WeChat");

                    b.HasKey("Id");

                    b.ToTable("Sys_UserInfo");

                    b.HasData(
                        new
                        {
                            Id = 111111L,
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 978, DateTimeKind.Unspecified).AddTicks(7463), new TimeSpan(0, 0, 0, 0, 0)),
                            HeadPortrait = "https://p1.music.126.net/RVcAosDFn4uLeSZ_byDGdg==/109951165726231133.jpg?param=1024y1024",
                            IsDeleted = false,
                            UserID = 156951674213412L,
                            UserShowName = "Admin"
                        });
                });

            modelBuilder.Entity("AdminBlog.Core.SysUserRole", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleID");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.ToTable("Sys_UserRole");

                    b.HasData(
                        new
                        {
                            Id = 156951674213412L,
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 12, 27, 14, 26, 24, 985, DateTimeKind.Unspecified).AddTicks(9301), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            RoleID = 156951674213412L,
                            UserID = 156951674213412L
                        });
                });

            modelBuilder.Entity("AdminBlog.Core.SysWaterfallImages", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("Src")
                        .HasColumnType("longtext");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sys_WaterfallImages");
                });
#pragma warning restore 612, 618
        }
    }
}
